# version: "3.8"

services:
  backend:
    build:
      context: ./back
      # target: final # используем финальный stage из многоступенчатой сборки
    ports:
      - "5005:5005"
    environment:
      # - DATABASE_URL=sqlite:file:./data/database.db
      - DATABASE_URL=sqlite:///app/data/database.db
    # - PORT=5000
    restart: unless-stopped
    volumes:
      # - .:/app
      # - type: bind
      # source: ./data/
      # target: /app/data/
      - ./src:/app/src
      - ./migrations:/app/migrations
      # - ./templates:/app/templates
      # - ./static:/app/static
      # Монтируем Cargo.toml и Cargo.lock
      # - app_data:/app/data
      - ./Cargo.toml:/app/Cargo.toml:ro
      - ./Cargo.lock:/app/Cargo.lock:ro
      # - ./data/test.txt:/app/data/test.txt
      # - ./data:/app/data
      # - ./data/database.db:/app/data/database.db:ro
      # - ./database.db:/app/database.db
      # - ./templates:/app/static
    networks:
      - app-network
  frontend:
    volumes:
      - ./front:/app
      # - frontend-node-modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ./front
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    # - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
# volumes:
# app_data:

networks:
  app-network:
    driver: bridge
